[tool.commitizen]
name = "cz_conventional_commits_ronmckay"
version = "1.0.1"
tag_format = "v$version"
update_changelog_on_bump = true
changelog_incremental = true
annotated_tag = true
use_shortcuts = true
